# Exercise 3

Two fair dice, one red and one blue, are thrown. For each die: the possible scores are 1,2,3,4,5,6. Each
score is equally likely, so each score has probability $\frac{1}{6}$. You may assume that the score on red die is
independent of the score on the blue die.

We define the following events: \
$A$: sum of the scores on the dice is 7. \
$B$: the score on the red die is different from the score on the blue die. \
$C$: the sum of the scores on the dice is 11. \
$D$: the score on the red die is 6. \

## Question 1
**(a) Calculate $P(A), P(B), P(C)$, and $P(D)$.**
$$P(A) = (\frac{1}{6} \cdot \frac{1}{6}) \cdot 6 = \frac{1}{6} \\
P(B) = \frac{5}{6} \\
P(C) = (\frac{1}{6} \cdot \frac{1}{6}) \cdot 2 = \frac{1}{18} \\
P(D) = \frac{1}{6}$$

**(b) Calculate $P(A,B), P(A,C)$, and $P(A,D)$.**
$$P(A,B) = P(A) = \frac{1}{6} \\
P(A,C) = 0 \\
P(A,D) = \frac{1}{6} \cdot \frac{1}{6} = \frac{1}{36}$$

**(c) Calculate $P(A or B), P(A or C)$, and $P(A or D)$.**
$$P(A \ or \ B) = P(B) = \frac{5}{6} \\
P(A \ or \  C) = P(A) + P(C) = \frac{1}{6} + \frac{1}{18} = \frac{2}{9} \\
P(A \ or \ D) = \frac{1}{6} + \frac{1}{6} \cdot \frac{5}{6} = \frac{11}{36}$$

**(d) Calculate $P(B \mid A), P(C \mid A)$, and $P(D \mid A)$.**
$$P(B \mid A) = \frac{P(A,B)}{P(A)} = 1 \\
P(C \mid A) = \frac{P(A,C)}{P(A)} = 0 \\
P(D \mid A) = \frac{P(A,D)}{P(A)} = \frac{\frac{1}{36}}{\frac{1}{6}} = \frac{1}{6}$$

## Question 2
**Which of the following pairs of events are independent and why?** \
**(a) A and B.** \
$P(A,B) = \frac{1}{6} \neq P(A) \cdot P(B)$, $\therefore A$ is not independent of $B$. \
Events $A$ and $B$ are not independent if $A$ happens (the sum of the scores on 2 dice equal 7), $B$ must happen since the score on the red die must be different from the score on the blue one. \

**(b) A and C.** \
$P(A,C) = 0$, $\therefore A$ is not independent of $C$. \
Events A and C are not independent, they are mutually exclusive since these 2 events cannot happen at the same time. \

**(c) A and D.** \
$P(A,D) = \frac{1}{6} \cdot \frac{1}{6} = \frac{1}{36}$, $\therefore A \perp B$. \
Events A and D are independent.

## Question 3
**Now let $E$ be the event that at least one 6 is thrown and $F$ the event that two 6s are thrown. Calculate:** \
**(a) $P(F \mid D)$.** \
$$P(F \mid D) = \frac{P(F,D)}{P(D)} = \frac{\frac{1}{6} \cdot \frac{1}{6}}{\frac{1}{6}} = \frac{1}{6}$$ \
**(b) $P(F \mid E)$.** \
$$P(F \mid E) = \frac{P(F,E)}{P(E)} = \frac{\frac{1}{6} \cdot \frac{1}{6}}{\frac{1}{6} \cdot \frac{1}{6} + \frac{1}{6} \cdot \frac{5}{6} \cdot 2} = \frac{1}{11}$$
 