# Exercise 4

## Question 1
**$B_1$ and $B_2$ are mutually exclusive, exhaustive events such that $P(B_1) = 0.05$. $A$ is an event such that $P(A \mid B_1) = 0.75$ and $P(A \mid B_2) = 0.50$.** \
**(a) Use the law of total probability to calculate $P(A)$.** \
$$P(A) = P(A \mid B_1)P(B_1) + P(A \mid B_2)P(B_2) = 0.75 * 0.05. + 0.50 * (1 - 0.05) = 0.5125$$ 
**(b) Use Bayes' Theorem to calculate $P(B_1 \mid A)$.** \
$$P(B_1 \mid A) = \frac{P(A \mid B_1) \cdot P(B_1)}{P(A)} = \frac{0.75 \cdot 0.05}{0.5125} = 0.07317$$

## Question 2
In a population, 5% of people have high blood pressure. Of people with high blood pressure, 75% drink alcohol whereas only 50% of people without high blood pressure drink alcohol. What percentage of drinkers of alcohol have high blood pressure? \

Let event $B_1$ represent people having high blood pressure in the population, whereas event $B_2$ represents people without high blood pressure in this population.
$$\therefore P(B_1) = 0.05, \ P(B_2) = 0.95.$$
Let event $A$ represent people who drink alcohol. Of people with high blood pressure, 75% drink alcohol while only 50% of people without high blood pressure drink alcohol.
$$\therefore P(A \mid B_1) = 0.75, \ P(A \mid B_2) = 0.50.$$
Therefore, the percentage of alcohol drinkers having high blood pressure can be interpreted as $PA(B_1 \mid A)$.
$$P(B_1 \mid A) = \frac{P(A \mid B_1) \cdot P(B_1))}{P(A)} = \frac{0.75 \cdot 0.05}{0.5125} = 0.07317$$

## Question 3
Suppose that $A$ and $B$ are two events with $P(A) > 0$ and $P(B) > 0$. Suppose, in addition, that $P(A \mid B) < P(A)$. Using Bayes' Theorem, or otherwise, show that $P(B \mid A) < P(B$. Interpret this result using words.
$$P(A \mid B) < P(A)$$
$$\frac{P(B \mid A) \cdot P(A)}{P(B)} < P(B)$$
$$\because P(A) > 0, P(B) > 0$$
$$\therefore \frac{P(B \mid A) \cdot P(B) \cdot P(A)}{P(B) \cdot P(A)} < \frac{P(A) \cdot P(B)}{P(A)}$$
$$\therefore P(B \mid A) < P(B)$$
Interpretation: the conditional probability will always be less than or at least equal to the total proabability of an event.

